name: BuildOnStep

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: install
        run: |
          pip install -U https://github.com/platformio/platformio-core/archive/refs/tags/v6.1.5.zip
          pio pkg install --global --platform espressif32
      - name: Create directory structure
        run: |
          rsync -r  --remove-source-files --exclude=".*" --exclude="platformio.ini"  src/* src/src
          find . -depth -type d -empty -delete
          mv *.h *.ino src/
      - name: Build
        run: |
          pio run
          ls -laR .
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          path: |
           - .
           
          
