name: BuildOnStep

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: install
        run: |
          pip install -U https://github.com/platformio/platformio-core/archive/refs/tags/v6.1.5.zip
          pio pkg install --global --platform espressif32
      - name: Create directory structure
        run: |
          rsync -r  --remove-source-files --exclude=".*" --exclude="platformio.ini"  src/* src/src
          find . -depth -type d -empty -delete
          mv *.h *.ino src/

      - name: libraries
        run: |
          pio pkg install --library https://github.com/mikalhart/TinyGPSPlus.git
          pio pkg install --library https://github.com/adafruit/Adafruit_Sensor.git
          pio pkg install --library https://github.com/adafruit/Adafruit_BME280_Library.git

      - name: Install library dependencies
        run: |
          wget https://github.com/Makuna/Rtc/archive/master.zip -O /tmp/rtc_master.zip
          unzip /tmp/rtc_master.zip -d /tmp/

      - name: Run PlatformIO
        run: pio ci src/ --lib="/tmp/Rtc-master" -c platformio.ini --keep-build-dir

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          path: .pio/build/esp32dev/firmware.bin
          
